// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public interface HelloI extends Ice.Object,
                                _HelloIOperations, _HelloIOperationsNC
{
    public static final String ice_staticId = "::slice2java::HelloI";

    public static final long serialVersionUID = 50463016L;
}
