// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ice.book.slice2java.message;

public interface SMSService extends Ice.Object,
                                    _SMSServiceOperations, _SMSServiceOperationsNC
{
    public static final String ice_staticId = "::message::SMSService";

    public static final long serialVersionUID = 358754726L;
}
