// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `entities_data_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package hjmos.EntitiesDataService;

public interface IDataUpdator extends Ice.Object,
                                      _IDataUpdatorOperations, _IDataUpdatorOperationsNC
{
    public static final String ice_staticId = "::hjmos::EntitiesDataService::IDataUpdator";

    public static final long serialVersionUID = -640317970L;
}
