// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `entities_data_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package hjmos.EntitiesDataService;

public final class IDataUpdatorHolder extends Ice.ObjectHolderBase<IDataUpdator>
{
    public
    IDataUpdatorHolder()
    {
    }

    public
    IDataUpdatorHolder(IDataUpdator value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IDataUpdator)
        {
            value = (IDataUpdator)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IDataUpdatorDisp.ice_staticId();
    }
}
