// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `entities_data_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package hjmos.EntitiesDataService;

/**
 * Provides type-specific helper functions.
 **/
public final class IDataUpdatorPrxHelper extends Ice.ObjectPrxHelperBase implements IDataUpdatorPrx
{
    private static final String __UpdateEntities_name = "UpdateEntities";

    public int UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data)
    {
        return UpdateEntities(cbId, interfaceId, info, data, null, false);
    }

    public int UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, java.util.Map<String, String> __ctx)
    {
        return UpdateEntities(cbId, interfaceId, info, data, __ctx, true);
    }

    private int UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__UpdateEntities_name);
        return end_UpdateEntities(begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, null, false, false, null);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, java.util.Map<String, String> __ctx)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, Ice.Callback __cb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, Callback_IDataUpdator_UpdateEntities __cb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, String interfaceId, LocatitionInfo info, java.util.Map<java.lang.String, java.lang.String> data, java.util.Map<String, String> __ctx, Callback_IDataUpdator_UpdateEntities __cb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, 
                                                String interfaceId, 
                                                LocatitionInfo info, 
                                                java.util.Map<java.lang.String, java.lang.String> data, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, 
                                                String interfaceId, 
                                                LocatitionInfo info, 
                                                java.util.Map<java.lang.String, java.lang.String> data, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, 
                                                String interfaceId, 
                                                LocatitionInfo info, 
                                                java.util.Map<java.lang.String, java.lang.String> data, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_UpdateEntities(String cbId, 
                                                String interfaceId, 
                                                LocatitionInfo info, 
                                                java.util.Map<java.lang.String, java.lang.String> data, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_UpdateEntities(String cbId, 
                                                 String interfaceId, 
                                                 LocatitionInfo info, 
                                                 java.util.Map<java.lang.String, java.lang.String> data, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.Functional_IntCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_UpdateEntities(cbId, interfaceId, info, data, __ctx, __explicitCtx, __synchronous, 
                                    new IceInternal.Functional_TwowayCallbackInt(__responseCb, __exceptionCb, __sentCb)
                                        {
                                            public final void __completed(Ice.AsyncResult __result)
                                            {
                                                IDataUpdatorPrxHelper.__UpdateEntities_completed(this, __result);
                                            }
                                        });
    }

    private Ice.AsyncResult begin_UpdateEntities(String cbId, 
                                                 String interfaceId, 
                                                 LocatitionInfo info, 
                                                 java.util.Map<java.lang.String, java.lang.String> data, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__UpdateEntities_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__UpdateEntities_name, __cb);
        try
        {
            __result.prepare(__UpdateEntities_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(cbId);
            __os.writeString(interfaceId);
            LocatitionInfo.__write(__os, info);
            EntitiesValueMapHelper.write(__os, data);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public int end_UpdateEntities(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __UpdateEntities_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __UpdateEntities_completed(Ice.TwowayCallbackInt __cb, Ice.AsyncResult __result)
    {
        hjmos.EntitiesDataService.IDataUpdatorPrx __proxy = (hjmos.EntitiesDataService.IDataUpdatorPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_UpdateEntities(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IDataUpdatorPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), IDataUpdatorPrx.class, IDataUpdatorPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IDataUpdatorPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), IDataUpdatorPrx.class, IDataUpdatorPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IDataUpdatorPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), IDataUpdatorPrx.class, IDataUpdatorPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IDataUpdatorPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), IDataUpdatorPrx.class, IDataUpdatorPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static IDataUpdatorPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, IDataUpdatorPrx.class, IDataUpdatorPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static IDataUpdatorPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, IDataUpdatorPrx.class, IDataUpdatorPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::hjmos::EntitiesDataService::IDataUpdator"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, IDataUpdatorPrx v)
    {
        __os.writeProxy(v);
    }

    public static IDataUpdatorPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            IDataUpdatorPrxHelper result = new IDataUpdatorPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
