// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `entities_data_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package hjmos.EntitiesDataService;

public interface IDataServiceAccessorPrx extends Ice.ObjectPrx
{
    public String Register(IDataUpdatorPrx cb);

    public String Register(IDataUpdatorPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, Ice.Callback __cb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, Callback_IDataServiceAccessor_Register __cb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, java.util.Map<String, String> __ctx, Callback_IDataServiceAccessor_Register __cb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_Register(IDataUpdatorPrx cb, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public String end_Register(Ice.AsyncResult __result);

    public boolean UnSubscribe(String cbId);

    public boolean UnSubscribe(String cbId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UnSubscribe(String cbId);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, Ice.Callback __cb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, Callback_IDataServiceAccessor_UnSubscribe __cb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, java.util.Map<String, String> __ctx, Callback_IDataServiceAccessor_UnSubscribe __cb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, 
                                             IceInternal.Functional_BoolCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, 
                                             IceInternal.Functional_BoolCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_BoolCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_UnSubscribe(String cbId, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_BoolCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_UnSubscribe(Ice.AsyncResult __result);

    public boolean UnSubscribeImpl(String cbId, String interfaceId);

    public boolean UnSubscribeImpl(String cbId, String interfaceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, String interfaceId);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, String interfaceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, String interfaceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, String interfaceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, String interfaceId, Callback_IDataServiceAccessor_UnSubscribeImpl __cb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, String interfaceId, java.util.Map<String, String> __ctx, Callback_IDataServiceAccessor_UnSubscribeImpl __cb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, 
                                                 String interfaceId, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, 
                                                 String interfaceId, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, 
                                                 String interfaceId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_UnSubscribeImpl(String cbId, 
                                                 String interfaceId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_UnSubscribeImpl(Ice.AsyncResult __result);

    public void QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray);

    public void QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray, Ice.Callback __cb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray, Callback_IDataServiceAccessor_QueryEntitiesValue __cb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, String interfaceId, LocatitionInfo info, String[] entitiesArray, java.util.Map<String, String> __ctx, Callback_IDataServiceAccessor_QueryEntitiesValue __cb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, 
                                                    String interfaceId, 
                                                    LocatitionInfo info, 
                                                    String[] entitiesArray, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, 
                                                    String interfaceId, 
                                                    LocatitionInfo info, 
                                                    String[] entitiesArray, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, 
                                                    String interfaceId, 
                                                    LocatitionInfo info, 
                                                    String[] entitiesArray, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_QueryEntitiesValue(String cbId, 
                                                    String interfaceId, 
                                                    LocatitionInfo info, 
                                                    String[] entitiesArray, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public void end_QueryEntitiesValue(Ice.AsyncResult __result);
}
