// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `book.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ice.book.slice2java;

public interface OnlineBookPrx extends Ice.ObjectPrx
{
    public void bookTick(String name, double price, String content);

    public void bookTick(String name, double price, String content, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bookTick(String name, double price, String content);

    public Ice.AsyncResult begin_bookTick(String name, double price, String content, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bookTick(String name, double price, String content, Ice.Callback __cb);

    public Ice.AsyncResult begin_bookTick(String name, double price, String content, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bookTick(String name, double price, String content, Callback_OnlineBook_bookTick __cb);

    public Ice.AsyncResult begin_bookTick(String name, double price, String content, java.util.Map<String, String> __ctx, Callback_OnlineBook_bookTick __cb);

    public Ice.AsyncResult begin_bookTick(String name, 
                                          double price, 
                                          String content, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bookTick(String name, 
                                          double price, 
                                          String content, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bookTick(String name, 
                                          double price, 
                                          String content, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bookTick(String name, 
                                          double price, 
                                          String content, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_bookTick(Ice.AsyncResult __result);
}
